# Default configuration for session in the general environment
framework:
    secret: '%env(APP_SECRET)%'

    error_controller: 'App\Controller\CustomErrorController::show'

    # Enable session handling globally
    session:
        handler_id: null  # Utilisation de la gestion native des sessions par défaut
        storage_factory_id: session.storage.factory.native  # Définir le type de stockage par défaut (native)

# Configuration spécifique pour l'environnement de test
when@test:
    framework:
        # Test spécifique
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file  # Utilise un mock pour les tests
