security:
    access_denied_url: /connexion
    # Gestion des hashages des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Définition du fournisseur d'utilisateurs
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider

            # Configuration du login formulaire
            form_login:
                login_path: connexion
                check_path: connexion

                username_parameter: email
                password_parameter: password

                # Gestionnaire personnalisé pour la redirection après connexion
                success_handler: App\Security\CustomAuthenticationSuccessHandler

            # Configuration de la déconnexion
            logout:
                path: deconnexion

    # Hiérarchie des rôles
    role_hierarchy:
        ROLE_ADMIN: [ROLE_CANDIDAT]

    # Règles d'accès
    access_control:
        - { path: '^/profilCandidat', roles: [IS_AUTHENTICATED_FULLY] }
        - { path: '^/profilEmployeur', roles: [IS_AUTHENTICATED_FULLY] }
        - { path: ^/supprimer-compte, roles: IS_AUTHENTICATED_FULLY }


when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10