security:
  access_denied_url: /connexion

  # Gestion des hashages des mots de passe
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  # Définition du fournisseur d'utilisateurs
  providers:
    app_user_provider:
      entity:
        class: App\Entity\Utilisateur
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: app_user_provider

      # Configuration du login formulaire
      form_login:
        login_path: connexion
        check_path: connexion
        username_parameter: email
        password_parameter: password

        # Gestionnaire personnalisé pour la redirection après connexion
        success_handler: App\Security\CustomAuthenticationSuccessHandler

      # Configuration de la déconnexion
      logout:
        path: deconnexion
        target: / # Redirige vers la page d'accueil

  # Hiérarchie des rôles
  role_hierarchy:
      ROLE_ADMIN: ROLE_ADMIN
      ROLE_CANDIDAT: ROLE_USER
      ROLE_EMPLOYEUR: ROLE_USER

  # Règles d'accès
  access_control:
    - { path: "^/admin", roles: [ROLE_ADMIN] }
    - { path: "^/mesIdentifiantsDeConnexionE", roles: IS_AUTHENTICATED_FULLY }
    - { path: "^/maFicheE", roles: [ROLE_EMPLOYEUR] }
    - { path: "^/supprimer-compteE", roles: [ROLE_EMPLOYEUR] }
    - { path: "^/confirmer_suppression-compteE", roles: [ROLE_EMPLOYEUR] }
    - { path: "^/profilCandidat", roles: IS_AUTHENTICATED_FULLY } 
    - { path: "^/maFiche", roles: [ROLE_CANDIDAT] }
    - { path: "^/modifierMesInformations", roles: [ROLE_CANDIDAT] }
    - { path: "^/mesCandidatures", roles: [ROLE_CANDIDAT] }
    - { path: "^/mesIdentifiantsDeConnexion", roles: [ROLE_CANDIDAT] }
    - { path: "^/postuler", roles: [ROLE_CANDIDAT] }
    - { path: "^/supprimer-compte", roles: [ROLE_CANDIDAT] }
    - { path: "^/confirmer_compte", roles: [ROLE_CANDIDAT] }
    - { path: "^/profilEmployeur", roles: [ROLE_EMPLOYEUR] }
    - { path: "^/poster-offre-emploi", roles: [ROLE_EMPLOYEUR] }
    - { path: "^/modifierMesInformationsE", roles: [ROLE_EMPLOYEUR] }
    - { path: "^/mesOffresE", roles: [ROLE_EMPLOYEUR] }
    - { path: "^/telecharger_cv", roles: [ROLE_EMPLOYEUR] }
    - { path: "^/telecharger_lettre_motivation", roles: [ROLE_EMPLOYEUR] }
    - { path: "^/supprimer_offre", roles: [ROLE_EMPLOYEUR] }
    - { path: "^/filtrer_candidatures", roles: [ROLE_EMPLOYEUR] }


when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10
