twig:
    file_name_pattern: '*.twig'
    globals:
        app_request: '@request_stack'

    form_themes: ['bootstrap_5_layout.html.twig']

    strict_variables: true

    default_path: '%kernel.project_dir%/templates'
