parameters:
    env(MONGODB_URL): '' # URL de connexion à MongoDB
    env(MONGODB_DB): ''  # Nom de la base MongoDB
    uploads_directory: '%kernel.project_dir%/public/uploads' # Répertoire des uploads
    upload_directory: '%kernel.project_dir%/public/uploads'  # Alternative pour le binding

services:
    # Configuration par défaut pour les services
    _defaults:
        autowire: true      # Injection automatique des dépendances
        autoconfigure: true # Enregistrement automatique comme commandes, listeners, etc.
        bind:
            $uploadsDirectory: '%uploads_directory%' # Exemple de liaison de paramètre


    # Enregistrement automatique des services dans src/
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Contrôleurs comme services
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # Services spécifiques ou externalisés
    App\Repository\:
        resource: '../src/Repository/'
        
    # l'implémentation du CustomAuthenticationSuccessHandler
    App\Security\CustomAuthenticationSuccessHandler:
        arguments:
            $router: '@router.default'
        tags:
            - { name: 'security.authentication.success_handler', priority: 100 }
